FROM node:14.17.0 as build
WORKDIR /info-scriptics-master

COPY package*.json .
RUN npm install
COPY . .

RUN npm run build
FROM nginx:1.19
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /info-scriptics-master/build /usr/share/nginx/html